WITH U2021 AS (
SELECT USER_ID
  FROM USER_INFO
 WHERE JOINED LIKE '2021%'  
)
SELECT YEAR(SALES_DATE) YEAR
     , MONTH(SALES_DATE) MONTH 
     , COUNT(DISTINCT USER_ID) PURCHASE_USERS
     , ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM U2021), 1) PURCHASED_RATIO
  FROM ONLINE_SALE
 WHERE USER_ID IN (SELECT USER_ID FROM U2021)
 GROUP BY YEAR, MONTH
 ORDER BY YEAR, MONTH;