SELECT EI1.ID
     , IFNULL(EI2.COUNT, 0) AS CHILD_COUNT
  FROM ECOLI_DATA EI1
  LEFT JOIN (SELECT COUNT(*) AS COUNT
                  , PARENT_ID
               FROM ECOLI_DATA 
              GROUP BY PARENT_ID) EI2 ON EI1.ID = EI2.PARENT_ID