SELECT DISTINCT C.CAR_ID 
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
  JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = RH.CAR_ID 
 WHERE C.CAR_TYPE = '세단'
   AND DATE_FORMAT(RH.START_DATE, '%Y-%m') = '2022-10'
 ORDER BY CAR_ID DESC;