SELECT A.AUTHOR_ID
     , A.AUTHOR_NAME
     , B.CATEGORY 
     , SUM(BS.SALES * B.PRICE) TOTAL_SALES 
  FROM BOOK_SALES BS
  JOIN BOOK B ON B.BOOK_ID = BS.BOOK_ID 
  JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
 WHERE MONTH(BS.SALES_DATE) = 1 
   AND YEAR(BS.SALES_DATE) = 2022
 GROUP BY B.CATEGORY, A.AUTHOR_ID, A.AUTHOR_NAME
 ORDER BY A.AUTHOR_ID, B.CATEGORY DESC;