SELECT M.FOOD_TYPE
      ,M.REST_ID
      ,M.REST_NAME
      ,M.FAVORITES
  FROM REST_INFO M
  JOIN (
        SELECT RI.FOOD_TYPE
              ,MAX(RI.FAVORITES) MAX_FAVORITES
          FROM REST_INFO RI
         GROUP BY RI.FOOD_TYPE
       ) S ON M.FAVORITES = S.MAX_FAVORITES
          AND M.FOOD_TYPE = S.FOOD_TYPE
 ORDER BY M.FOOD_TYPE DESC