SELECT DATE_FORMAT(OS.SALES_DATE, '%Y') YEAR
     , CONVERT(DATE_FORMAT(OS.SALES_DATE, '%c'), SIGNED INTEGER) MONTH
     , UI.GENDER
     , COUNT(DISTINCT OS.USER_ID) USERS
  FROM ONLINE_SALE OS
  JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
 WHERE UI.GENDER IS NOT NULL
 GROUP BY YEAR, MONTH, UI.GENDER
 ORDER BY YEAR, MONTH, UI.GENDER;