SELECT RI.FOOD_TYPE
     , RI.REST_ID
     , RI.REST_NAME
     , RI.FAVORITES
  FROM REST_INFO RI
  JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) FAVORITES FROM REST_INFO GROUP BY FOOD_TYPE) RIM ON RI.FAVORITES = RIM.FAVORITES AND RI.FOOD_TYPE = RIM.FOOD_TYPE
 ORDER BY RI.FOOD_TYPE DESC;