SELECT TO_NUMBER(TO_CHAR(SALES_DATE, 'YYYY')) AS YEAR
      ,TO_NUMBER(TO_CHAR(SALES_DATE, 'MM'))   AS MONTH
      ,UI.GENDER
      ,COUNT(DISTINCT OS.USER_ID) AS USERS
  FROM ONLINE_SALE OS
  JOIN USER_INFO UI ON OS.USER_ID = UI.USER_ID
 WHERE UI.GENDER IS NOT NULL
 GROUP BY YEAR
         ,MONTH
         ,UI.GENDER
 ORDER BY YEAR
         ,MONTH
         ,UI.GENDER