SELECT FO.PRODUCT_ID 
     , FP.PRODUCT_NAME 
     , SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALE
  FROM FOOD_PRODUCT FP
  JOIN FOOD_ORDER FO ON FO.PRODUCT_ID = FP.PRODUCT_ID
 WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
 GROUP BY FP.PRODUCT_ID
 ORDER BY TOTAL_SALE DESC, FO.PRODUCT_ID;