SELECT SD.ROUTE
     , CONCAT(ROUND(SUM(SD.D_BETWEEN_DIST), 1), 'km') AS TOTAL_DISTANCE
     , CONCAT(ROUND(AVG(SD.D_BETWEEN_DIST), 2), 'km') AS AVERAGE_DISTANCE
  FROM SUBWAY_DISTANCE SD
 GROUP BY SD.ROUTE
 ORDER BY SUM(SD.D_BETWEEN_DIST) DESC