SELECT EXTRACT(YEAR FROM OS.SALES_DATE)  AS YEAR
      ,EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH
      ,COUNT(DISTINCT UI.USER_ID)        AS PURCHASED_USERS
      ,ROUND(
          COUNT(DISTINCT UI.USER_ID) / (SELECT COUNT(1)
                                          FROM USER_INFO UI
                                         WHERE EXTRACT(YEAR FROM JOINED) = 2021) 
          , 1
            ) AS PUCHASED_RATIO
  FROM ONLINE_SALE OS
  JOIN (SELECT UI.USER_ID
          FROM USER_INFO UI
         WHERE EXTRACT(YEAR FROM JOINED) = 2021) UI ON OS.USER_ID = UI.USER_ID
  GROUP BY YEAR,MONTH
  ORDER BY YEAR,MONTH

