WITH RECURSIVE ED AS(
    SELECT ID AS ID
         , 0 AS PARENT_ID
         , 1 AS GENERATION
      FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    UNION ALL
    SELECT ED2.ID
         , ED2.PARENT_ID
         , ED.GENERATION + 1 
      FROM ECOLI_DATA ED2
      JOIN ED ON IFNULL(ED2.PARENT_ID, 0) = ED.ID
)  
SELECT COUNT(*) AS COUNT
     , GENERATION
  FROM ED AS ED1
 WHERE NOT EXISTS (
    SELECT 1
      FROM ED AS ED2
     WHERE ED1.ID = ED2.PARENT_ID
 )
 GROUP BY GENERATION
 ORDER BY GENERATION