-- 코드를 입력하세요
SELECT UGU.USER_ID
     , UGU.NICKNAME
     , UGB.TOTAL_SALES
  FROM USED_GOODS_USER UGU
  JOIN (SELECT SUM(UGB.PRICE)  AS TOTAL_SALES
             , UGB.STATUS
             , UGB.WRITER_ID
          FROM USED_GOODS_BOARD UGB 
         GROUP BY UGB.WRITER_ID, UGB.STATUS
        HAVING UGB.STATUS = 'DONE') AS UGB ON UGU.USER_ID = UGB.WRITER_ID
 WHERE UGB.TOTAL_SALES >= 700000
 ORDER BY UGB.TOTAL_SALES