-- 코드를 입력하세요
SELECT UGU.USER_ID
     , UGU.NICKNAME
     , SUM(UGB.PRICE) TOTAL_SALES
  FROM USED_GOODS_USER UGU
  JOIN USED_GOODS_BOARD UGB ON UGU.USER_ID = UGB.WRITER_ID
 WHERE UGB.STATUS = 'DONE'
 GROUP BY UGU.USER_ID
 HAVING TOTAL_SALES >= 700000
 ORDER BY TOTAL_SALES