SELECT FP.PRODUCT_ID
      ,FP.PRODUCT_NAME
      ,(SUM(FO.AMOUNT) * FP.PRICE) AS TOTAL_SALES
  FROM FOOD_ORDER FO
  JOIN FOOD_PRODUCT FP ON FP.PRODUCT_ID = FO.PRODUCT_ID
 WHERE FO.PRODUCE_DATE BETWEEN TO_DATE('2022-05-01', 'YYYY-MM-DD')
                           AND TO_DATE('2022-05-31', 'YYYY-MM-DD')
 GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE
 ORDER BY TOTAL_SALES DESC, FP.PRODUCT_ID