SELECT SALES_DATE, PRODUCT_ID, USER_ID, SALES_AMOUNT
  FROM (SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE, 
               PRODUCT_ID, 
               USER_ID,
               SALES_AMOUNT 
          FROM ONLINE_SALE
         UNION ALL 
        SELECT TO_CHAR(SALES_DATE, 'YYYY-MM-DD') SALES_DATE,
               PRODUCT_ID, 
               NULL USER_ID, 
               SALES_AMOUNT 
         FROM OFFLINE_SALE)
 WHERE SALES_DATE LIKE '2022-03%'
ORDER BY 1, 2, 3;