SELECT UGU.USER_ID     AS USED_ID
      ,UGU.NICKNAME    AS NICKNAME
      ,UGB.TOTAL_SALES AS TOTAL_SALES
  FROM USED_GOODS_USER UGU
  JOIN (
        SELECT SUM(PRICE) AS TOTAL_SALES
              ,WRITER_ID
          FROM USED_GOODS_BOARD
         WHERE STATUS = 'DONE'
         GROUP BY WRITER_ID
       ) UGB ON UGB.WRITER_ID = UGU.USER_ID
            AND UGB.TOTAL_SALES >= 700000
 ORDER BY UGB.TOTAL_SALES
