WITH RR AS(
    SELECT *
      FROM (
          SELECT COUNT(1)  AS REVIEW_COUNT
                ,RR_MAX.MEMBER_ID  
            FROM REST_REVIEW RR_MAX
           GROUP BY RR_MAX.MEMBER_ID
           ORDER BY REVIEW_COUNT DESC
            )
     WHERE ROWNUM = 1

)
SELECT MP.MEMBER_NAME 
      ,RR_M.REVIEW_TEXT 
      ,TO_CHAR(RR_M.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
  FROM RR
  JOIN MEMBER_PROFILE MP ON MP.MEMBER_ID = RR.MEMBER_ID
  JOIN REST_REVIEW RR_M ON RR.MEMBER_ID = RR_M.MEMBER_ID
 ORDER BY RR_M.REVIEW_DATE, RR_M.REVIEW_TEXT;