SELECT II2.ITEM_ID
     , II2.ITEM_NAME
     , II2.RARITY
  FROM ITEM_INFO II
  JOIN ITEM_TREE IT ON II.ITEM_ID = IT.PARENT_ITEM_ID
  JOIN ITEM_INFO II2 ON IT.ITEM_ID = II2.ITEM_ID  
 WHERE II.RARITY = 'RARE'
 ORDER BY II2.ITEM_ID DESC;