SELECT AI.NAME
     , AI.`DATETIME` 
  FROM ANIMAL_INS AI
 WHERE ANIMAL_ID NOT IN (SELECT AI.ANIMAL_ID 
                           FROM ANIMAL_INS AI
                           JOIN ANIMAL_OUTS AO ON AI.ANIMAL_ID = AO.ANIMAL_ID)
 ORDER BY `DATETIME`
 LIMIT 3;