SELECT S.MONTH
      ,S.CAR_ID
      ,S.RECORDS
  FROM (
        SELECT CAR_ID
              ,COUNT(1) RECORDS
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
         WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
         GROUP BY CAR_ID
         HAVING RECORDS >= 5
       ) M
  JOIN (
        SELECT CAR_ID
              ,EXTRACT(MONTH FROM START_DATE) AS MONTH
              ,COUNT(1) RECORDS
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
         WHERE EXTRACT(MONTH FROM START_DATE) BETWEEN 8 AND 10
         GROUP BY CAR_ID, MONTH
       ) S ON M.CAR_ID = S.CAR_ID
  WHERE S.RECORDS > 0
  ORDER BY MONTH, CAR_ID DESC