SELECT D.ID
     , D.EMAIL
     , D.FIRST_NAME
     , D.LAST_NAME
  FROM DEVELOPERS D
  JOIN SKILLCODES S ON S.NAME IN ('Python', 'C#')
                   AND S.CODE & D.SKILL_CODE > 0
 GROUP BY D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
 ORDER BY D.ID
  


