SELECT FP.CATEGORY AS CATEGORY
     , FP.PRICE AS MAX_PRICE
     , FP.PRODUCT_NAME AS PRODUCT_NAME
  FROM FOOD_PRODUCT FP
  JOIN (SELECT CATEGORY
             , MAX(PRICE) MAX_PRICE
          FROM FOOD_PRODUCT
         GROUP BY CATEGORY) FP2 
    ON FP.PRICE = FP2.MAX_PRICE
   AND FP.CATEGORY = FP2.CATEGORY
 WHERE FP2.CATEGORY IN('과자', '국', '김치', '식용유')
 ORDER BY MAX_PRICE DESC;