SELECT DISTINCT H.CAR_ID
     , CASE WHEN R.RENTED > 0 THEN '대여중'
       ELSE '대여 가능' END
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
  LEFT JOIN (SELECT COUNT(*) RENTED
                  , CAR_ID 
               FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
              WHERE '2022-10-16' BETWEEN START_DATE AND END_DATE
              GROUP BY CAR_ID) R
         ON H.CAR_ID = R.CAR_ID
 ORDER BY H.CAR_ID DESC;