WITH RECURSIVE TIME AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR+1 FROM TIME WHERE HOUR < 23
) 
SELECT T.HOUR
     , IFNULL(CT.COUNT, 0)
  FROM TIME T
  LEFT JOIN (SELECT HOUR(DATETIME) HOUR
                  , COUNT(HOUR(`DATETIME`)) COUNT
               FROM ANIMAL_OUTS
              GROUP BY HOUR(`DATETIME`)) CT
    ON T.HOUR = CT.HOUR;