SELECT CRCC.CAR_ID
  FROM CAR_RENTAL_COMPANY_CAR            CRCC
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
 WHERE CRCRH.START_DATE BETWEEN TO_DATE('2022-10-01', 'YYYY-MM-DD') 
                            AND TO_DATE('2022-10-31', 'YYYY-MM-DD')
   AND CRCC.CAR_TYPE = '세단'
 GROUP BY CRCC.CAR_ID
 ORDER BY CRCC.CAR_ID DESC;