WITH MAX_FISH AS (
    SELECT FNI.FISH_NAME
     , MAX(FI.LENGTH) AS LENGTH
  FROM FISH_INFO FI
  JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
 GROUP BY FNI.FISH_NAME
)
SELECT FI.ID
     , FNI.FISH_NAME
     , FI.LENGTH
  FROM FISH_INFO FI
  JOIN FISH_NAME_INFO FNI ON FI.FISH_TYPE = FNI.FISH_TYPE
  JOIN MAX_FISH MF ON FNI.FISH_NAME = MF.FISH_NAME
                  AND FI.LENGTH = MF.LENGTH
 ORDER BY FI.ID
