WITH CT AS (SELECT MEMBER_ID
                 , COUNT(*) COUNTED
              FROM REST_REVIEW
             GROUP BY MEMBER_ID)
SELECT MP.MEMBER_NAME 
     , R.REVIEW_TEXT
     , DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d')
  FROM REST_REVIEW R
  JOIN MEMBER_PROFILE MP ON R.MEMBER_ID = MP.MEMBER_ID
  JOIN CT ON MP.MEMBER_ID = CT.MEMBER_ID
 WHERE CT.COUNTED = (SELECT MAX(COUNTED) FROM CT)
 ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;