SELECT B.CATEGORY
      ,SUM(BS.SALES) AS TOTAL_SALES
  FROM BOOK B
  JOIN BOOK_SALES BS ON B.BOOK_ID = BS.BOOK_ID
 WHERE BS.SALES_DATE BETWEEN TO_DATE('2022-01-01','YYYY-MM-DD') AND TO_DATE('2022-01-31','YYYY-MM-DD')
 GROUP BY B.CATEGORY
 ORDER BY B.CATEGORY 