SELECT CASE WHEN GROUP_CONCAT(S.NAME) LIKE '%Python%'   
                 AND GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' THEN 'A'
            WHEN GROUP_CONCAT(S.NAME) LIKE '%C#%' THEN 'B'
            WHEN GROUP_CONCAT(S.CATEGORY) LIKE '%Front End%' THEN 'C' 
            END AS GRADE
     , D.ID
     , D.EMAIL
  FROM DEVELOPERS D
  JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE > 0
 GROUP BY D.ID, D.EMAIL
 HAVING GRADE IS NOT NULL
 ORDER BY GRADE, D.ID;